name: Deploy to Cloud Functions (Firebase)
on:
  push:
    branches:
      - main
    path:
      - "functions/cron/**"
      - ".github/workflows/deploy-cron.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: hu-tao-supremacy-305006
          service_account_key: ${{ secrets.CLOUD_FUNCTIONS_CREDENTIALS }}
          export_default_credentials: true
      - run: sudo npm install -g firebase-tools
      - run: |
          cd functions/cron
          yarn
          firebase deploy --debug --only functions
