name: Deploy to Cloud Functions
on: [push]
jobs:
  deploy-scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: scheduler
          runtime: node12
          credentials: ${{ secrets.CLOUD_FUNCTIONS_CREDENTIALS }}
          memory_mb: 1024
          region: asia-east2
          max_instances: 1
          source_dir: functions/cron
  deploy-personalization:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: personalization
          runtime: python37
          credentials: ${{ secrets.CLOUD_FUNCTIONS_CREDENTIALS }}
          memory_mb: 1024
          region: asia-east2
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/hu-tao-supremacy-305006/topics/fibonacci
          max_instances: 1
          source_dir: functions/personalization
