name: Deploy to Cloud Functions
on: [push]
jobs:
  deploy:
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: personalization
          runtime: python37
          credentials: ${{ secrets.CLOUD_FUNCTIONS_CREDENTIALS }}
          memory_mb: 1024
          region: asia-northeast1
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/${{ secrets.PROJECT_ID }}/topics/${{ secrets.TOPIC_ID }}
          max_instances: 1
