name: Deploy to Cloud Functions
on:
  push:
    branches:
      - main
    paths:
      - "functions/personalization/**"
      - ".github/workflows/deploy-cf.yaml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: hu-tao-supremacy-305006
          service_account_key: ${{ secrets.CLOUD_FUNCTIONS_CREDENTIALS }}
          export_default_credentials: true
      - uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: personalization
          runtime: python37
          memory_mb: 1024
          region: asia-east2
          event_trigger_type: google.pubsub.topic.publish
          event_trigger_resource: projects/hu-tao-supremacy-305006/topics/fibonacci
          max_instances: 1
          source_dir: functions/personalization
